apiVersion: operators.coreos.com/v1beta1
kind: ClusterServiceVersion
metadata:
  annotations:
    features.operators.openshift.io/fips-compliant: "true"
    alm-examples: '[]'
    capabilities: Basic Install
    features.operators.openshift.io/disconnected: "true"
    operatorframework.io/suggested-namespace: openstack
    operators.openshift.io/infrastructure-features: '["disconnected"]'
    operators.operatorframework.io/operator-type: non-standalone
  name: horizon-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Horizon is the Schema for the horizons API
      displayName: Horizon
      kind: Horizon
      name: horizons.horizon.openstack.org
      version: v1beta1
  description: Horizon Operator
  displayName: Horizon Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - OpenStack
  - UI
  - Horizon
  links:
  - name: Horizon Operator
    url: https://github.com/openstack-k8s-operators/horizon-operator
  maturity: beta
  provider:
    name: Red Hat Inc.
    url: https://redhat.com/
  version: 0.0.0
